--liquibase formatted sql
--changeset daniil.sudzhaev:0000_init.yaml
CREATE TABLE profile (
 	id BIGSERIAL PRIMARY KEY,
 	timezone VARCHAR(8) NOT NULL,
 	startpoint TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
 	endpoint TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT '3000-01-01T00:00:00Z'
);

CREATE TABLE dictionary (
 	id BIGSERIAL PRIMARY KEY,
 	profile_id BIGINT NOT NULL REFERENCES profile(id),
 	source_lang VARCHAR(8) NOT NULL,
 	target_lang VARCHAR(8) NOT NULL,
 	startpoint TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
 	last_updated_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
 	endpoint TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT '3000-01-01T00:00:00Z'
);

CREATE TABLE dictionary_record (
 	id BIGSERIAL PRIMARY KEY,
 	dictionary_id BIGINT NOT NULL REFERENCES dictionary(id),
 	startpoint TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
 	last_updated_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
 	endpoint TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT '3000-01-01T00:00:00Z'
);

CREATE TYPE LANGUAGE_DIRECTION AS ENUM ('source', 'target');

CREATE TABLE word (
 	id BIGSERIAL PRIMARY KEY,
 	record_id BIGINT NOT NULL REFERENCES dictionary_record(id),
 	content TEXT NOT NULL,
 	lang LANGUAGE_DIRECTION NOT NULL,
 	startpoint TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
 	endpoint TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT '3000-01-01T00:00:00Z'
);
